[theme]
primaryColor = "#d90429"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
